server:
  port: 9999
spring:x
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: buctcs1802
    password: cs1802..
    url: jdbc:mysql://8.140.3.158:3306/museum?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        mapper:
          debug
